version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS:  PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    expose:
      - 29092

  kafka-ui:
    container_name: kafka-ui
    image: "provectuslabs/kafka-ui:latest"
    ports:
      - "8084:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - zookeeper
      - kafka

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres"]

  producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONN: kafka:29092
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      KAFKA_TOPIC: orders.event.request
      SERVER_ADDRESS: 0.0.0.0:8080
    depends_on:
      - kafka
    command: sh -c "./bin/wb_service"

  consumer:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    ports:
      - "8082:8080"
    environment:
      KAFKA_CONN: kafka:29092
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      KAFKA_TOPIC: orders.event.response
      POSTGRES_CONN: "host=db port=5432 user=postgres password=1 dbname=postgres sslmode=disable"
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: 1
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      SERVER_ADDRESS: 0.0.0.0:8080
    depends_on:
      - kafka
      - db
    command: sh -c "./bin/wb_service"

volumes:
  postgres_data:
