DROP TABLE IF EXISTS employee CASCADE ;
DROP TYPE IF EXISTS organization_type CASCADE ;
DROP TABLE IF EXISTS organization CASCADE ;
DROP TABLE IF EXISTS organization_responsible CASCADE ;

DROP TYPE IF EXISTS service_type CASCADE ;
DROP TYPE IF EXISTS tender_status CASCADE ;

DROP TABLE IF EXISTS tender CASCADE ;
DROP TABLE IF EXISTS tender_condition CASCADE ;

DROP TYPE IF EXISTS bid_status CASCADE ;
DROP TYPE IF EXISTS bid_decision CASCADE ;
DROP TYPE IF EXISTS bid_author_type CASCADE ;

DROP TABLE IF EXISTS bid CASCADE ;
DROP TABLE IF EXISTS bid_condition CASCADE ;
DROP TABLE IF EXISTS bid_feedback CASCADE ;